### ISSUE TITLE
NPE in Gateway while killing an agent

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage#113]
```
Exception in thread "GatewayAgent@11714917" java.lang.NullPointerException
	at org.arl.fjage.remote.SlaveContainer.updateWatchList(SlaveContainer.java:332)
	at org.arl.fjage.remote.SlaveContainer.unsubscribe(SlaveContainer.java:280)
	at org.arl.fjage.Container.kill(Container.java:285)
	at org.arl.fjage.remote.SlaveContainer.kill(SlaveContainer.java:261)
	at org.arl.fjage.Agent.run(Agent.java:781)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mchitre** [comment]
`master` was nulled during closing of agent, while watch list was still being updated. Synchronization added to avoid the NPE, although the NPE was quite harmless.
