### ISSUE TITLE
fjageJSTest fails often on CI on Ubuntu

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage#168]
fjageJSTest seems to fail very often on CI on Ubuntu (passed on Windows always) for no apparent reason. Often passes if re-run. Can you take a look?

**Comment by notthetup** [comment]
```
org.arl.fjage.test.fjagejsTest > fjageJSTest FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.junit.Assert$assertTrue.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:208)
        at org.arl.fjage.test.fjagejsTest.fjageJSTest(fjagejsTest.groovy:100)
```

**Comment by notthetup** [comment]
```
org.arl.fjage.test.BasicTests > testParam2 FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.arl.fjage.test.BasicTests.testParam2(BasicTests.java:540)
```

**Comment by mchitre** [comment]
Yes, saw the `testParam1` failure once on my machine, but haven't been able to replicate it. Will track those 2 down if I see them again.
