### ISSUE TITLE
Remote container over serial port not working in fjage 1.5

### ISSUE THREAD

**Issue by prasadtiru** [org-arl/fjage#59]
The steps to reproduce:

1. Start the server 

```
❯ ./fjage.sh -rs232 /dev/tty.SLAB_USBtoUART -baud 115200
Exception in thread "serial:[closed]" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.arl.fjage.remote.ConnectionHandler.run(ConnectionHandler.java:47)
> ps
shell: org.arl.fjage.shell.ShellAgent - RUNNING
```
2. Start the remote container

```
❯ ./rconsole-rs232.sh /dev/tty.usbserial 115200
> Exception in thread "serial:[closed]" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.arl.fjage.remote.ConnectionHandler.run(ConnectionHandler.java:47)
Exception in thread "serial:[closed]" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.arl.fjage.remote.ConnectionHandler.run(ConnectionHandler.java:47)
Exception in thread "serial:[closed]" java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at org.arl.fjage.remote.ConnectionHandler.run(ConnectionHandler.java:47)
```

I figured something broke after the commit 9be88db6c6c828afdbb312c31c37291d9fc95568 . It works before that commit.

**Comment by mchitre** [comment]
@prasadtiru: fixed, please test and close the issue

**Comment by prasadtiru** [comment]
Tested. Fix works.
