### ISSUE TITLE
Refreshing a webpage using fjage.js multiple times causes Gateway to not work

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#69]
Refreshing a webpage using fjage.js multiple times causes Gateway to give timeout errors. Looking at logs on the server side shows this.

```
Exception in thread "OutputThread:ws:[80:/ws]" org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, current state [CLOSED], expecting [OPEN or CONNECTED]
	at org.eclipse.jetty.websocket.common.WebSocketSession.getRemote(WebSocketSession.java:411)
	at org.arl.fjage.connectors.WebSocketConnector$WSHandler.write(WebSocketConnector.java:246)
	at org.arl.fjage.connectors.WebSocketConnector$OutputThread.run(WebSocketConnector.java:171)
```

Seems like a synchronization issue with WSHandler's `onClose` and `write` methods.

**Comment by mchitre** [comment]
Not a sync issue, but simply that `write()` gives a `WebSocketException` instead of the `IOException` that the code was expecting. Fixed. @notthetup Can you please test?

**Comment by notthetup** [comment]
Testing with this in console instead of refreshing.. :)

```id = window.setInterval(() => {window.fjage.gateways[0].close(); console.log('new'); gw = new Gateway();}, 100)```

Looks good now.

Seeing a bunch of 

```
1550127975474|WARNING|org.arl.fjage.connectors.WebSocketConnector@21:write|RemoteEndpoint unavailable, current state [CLOSED], expecting [OPEN or CONNECTED]
```

but no crashes.
